pid: tmp/pids/thin.3000.pid
address: 127.0.0.1
timeout: 30
wait: 30
port: 3000
log: log/thin.log
max_conns: 64
require: []

environment: production
max_persistent_conns: 64
server: 1
daemonize: true
chdir: /opt/apps/todo/current
